### PR TITLE
fix(gemspec): Fix activesupport dependency

### PR DESCRIPTION
**Pull request by emilioeduardob**
It was not working on projects with rails 4.X.

### CODE REVIEW

**Comment by blackjid** [comment]
mm, did you tried the change with a rails 3.x project?

**Comment by emilioeduardob** [comment]
nope =(, I can try later

**Comment by blackjid** [comment]
@emilioeduardob I tried and it doesn't work... if you change it to `'>= 3.0'` we are good to go

**Comment by emilioeduardob** [comment]
silly me.. yup... `>=` is what I originally wanted hehehe =)

**Pull request merged**
